- apps/ello_search/lib/ello_search/post/search.ex
- We were passing this value is from the DiscoveryPost controller; however,
in order for this to override and be merged into the struct, we needed to
have the key already existing.
> Add default within_days value to search struct

- apps/ello_dispatch/lib/ello_dispatch/endpoint.ex
- apps/ello_v2/lib/ello_v2/endpoint.ex
- apps/ello_v2/test/controllers/following_post_controller_test.exs
- apps/ello_v2/web/controllers/following_post_controller.ex
- apps/ello_v2/web/router.ex
Support HEAD /api/v2/following/posts/recent (first page only)
Returns 304 if no new posts, returns 204 if there is new content.
With this merged we can remove all stream reading stuff from the mothership completely.
> Add following posts new content polling support.

- apps/ello_core/lib/ello_core/discovery.ex
Happens if post does not match query context. (private, blocked, nudity, etc)
> Filter out editorials with missing posts.

- apps/ello_feeds/test/controllers/editorial_controller_test.exs
- apps/ello_feeds/web/views/editorial_view.ex
We are seeing inconsistent inclusion of / separating host and path in
test/prod. This should ensure consistent formatting.
> Fix RSS links

- apps/ello_serve/lib/ello_serve/default_to_html.ex
- apps/ello_serve/web/router.ex
Phoenix throws errors if there is no matching accept headers.
Unfortunately there are many terrible clients/crawlers out there
requesting content without an accept header. In that case we add the
wildcard, to which phoenix will serve html.
https://app.honeybadger.io/projects/51139/faults/33289282/7fc60a64-61ab-11e7-84f1-a2a472b408ba#notice-summary
> Add default accept header (*/*).

- apps/ello_serve/lib/ello_serve/render.ex
Because this happens in process we don't need to measure independently.
We are currently getting double measurements here, resulting in segments
larger then the total time.
> Don't double count query times.

- apps/ello_serve/lib/ello_serve/render.ex
- apps/ello_serve/lib/ello_serve/skip_prerender.ex
- apps/ello_serve/test/controllers/webapp/no_content_controller_test.exs
- apps/ello_serve/web/templates/webapp/config/script.html.eex
- apps/ello_serve/web/views/webapp/config_view.ex
Adding debug=true or debug=false to a url should set the APP_DEBUG env param in webapp. Allows debugging of issues in production. If nil it defaults to the value in the environment variable.
> Add ?debug param to enable react app debug.

- apps/ello_serve/config/config.exs
Some clients send accept headers like:
text/*,application/xhtml+xml,application/xml,application/x-httpd-php
Which throws an error and 500 to the client:
https://app.honeybadger.io/projects/51139/faults/33289282/f4791f0e-6d7c-11e7-9939-b3d1bb1cb392#notice-summary
> Try to fix text/* mime type errors.

- apps/ello_serve/web/controllers/webapp/artist_invite_show_controller.ex
We must always have our standard params present for our preloads to
properly execute.
> Fix artist invite show logged out.

- apps/ello_core/lib/ello_core/contest.ex
- apps/ello_serve/test/controllers/webapp/artist_invite_show_controller_test.exs
- apps/ello_serve/web/controllers/webapp/artist_invite_show_controller.ex
- apps/ello_serve/web/templates/webapp/artist_invite_show/noscript.html.eex
- apps/ello_serve/web/views/webapp/artist_invite_show_view.ex
Selected submissions needed to be loaded with the standard_params, otherswise preloading failed.
We also need to take into account situations in which a post/author was filtered out (private, blocked, nsfw, etc) and ensure it did not error.
> Fix invite show page.

- .gitignore
- apps/ello_core/lib/ello_core/contest/artist_invite.ex
- apps/ello_v2/lib/ello_v2/conditional_get.ex
- apps/ello_v2/web/views/artist_invite_view.ex
This just mitigates an issue when the status rolls over because of the
time while the invite itself has not been updated.
https://www.pivotaltracker.com/story/show/150598853
> Bust Artist Invite cache when status updates.

- apps/ello_core/lib/ello_core/contest.ex
- apps/ello_v2/test/controllers/artist_invite_controller_test.exs
- apps/ello_v2/web/controllers/artist_invite_controller.ex
- apps/ello_v2/web/views/artist_invite_view.ex
We should not require the "preview" flag on show, just only show if
preview and staff/brand user.
> Fix preview logic.

- apps/ello_v2/test/controllers/following_post_controller_test.exs
- apps/ello_v2/web/controllers/following_post_controller.ex
- apps/ello_v2/web/router.ex
If you are staff, you can fetch another user's stream using the `/following/user/:id/posts/recent` endpoint.
[Finishes #152216687](https://www.pivotaltracker.com/story/show/152216687)
> Adds ability to see another user's following stream

- apps/ello_v2/lib/ello_v2/pagination.ex
- apps/ello_v2/web/controllers/artist_invite_controller.ex
- apps/ello_v2/web/controllers/editorials_controller.ex
The default of `per_page: 20` is only being used by iOS, but it breaks infinite scroll because that `20` *isn't* being in pagination.ex, so the system default 25 is used there instead, which triggers a "not enough items - no more pages" bug.
[Finishes #152762802](https://www.pivotaltracker.com/story/show/152762802)
> Quick fix for Artist Invite pagination

- apps/ello_v3/lib/ello_v3/middleware/standardize_arguments.ex
- apps/ello_v3/lib/ello_v3/schema/network_types.ex
- apps/ello_v3/test/ello_v3/resolvers/find_post_test.exs
- apps/ello_v3/test/ello_v3/resolvers/user_post_stream_test.exs
We were getting an extra nesting level we didn't want, for example:
%{author: %{user: %{current_user_state: %{}}}}
Instead of:
%{author: %{current_user_state: %{}}}
> Fix preloads from fragments.

- apps/ello_v3/lib/ello_v3/resolvers/subscribed_post_stream.ex
- apps/ello_v3/test/ello_v3/resolvers/subscribed_post_stream_test.exs
Prevents elastic search returning results on trending even when not
subscribed.
> Explicitly return nothing once unsubscribed.

- apps/ello_v2/test/controllers/post_view_controller_test.exs
- apps/ello_v2/web/controllers/post_view_controller.ex
Tokens and IDs do not come in as an array as recognized by Plug, so
parse and format as a list as appropriate.
> Handle post view API list handling.

- apps/ello_core/lib/ello_core/network/preload.ex
Don't 500 in this case, just treat the request as un-authenticated and
401.
> If token is invalid, user will be nil.

- apps/ello_core/lib/ello_core/discovery.ex
- apps/ello_core/lib/ello_core/discovery/category.ex
- apps/ello_core/lib/ello_core/discovery/preload.ex
- apps/ello_v3/lib/ello_v3/middleware/standardize_arguments.ex
- apps/ello_v3/lib/ello_v3/resolvers/category.ex
- apps/ello_v3/lib/ello_v3/resolvers/category_users.ex
- apps/ello_v3/lib/ello_v3/resolvers/find_post.ex
- apps/ello_v3/lib/ello_v3/schema.ex
- apps/ello_v3/lib/ello_v3/schema/discovery_types.ex
- apps/ello_v3/test/ello_v3/resolvers/category_test.exs
- apps/ello_v3/test/ello_v3/resolvers/find_post_test.exs
- apps/ello_v3/test/ello_v3/schema_test.exs
Category Users can be included in any category query and filtered by
role. We also add a query for getting a single category at a time.
> Adds category_user to category queries.

- apps/ello_v3/lib/ello_v3/resolvers/comment_stream.ex
- apps/ello_v3/test/ello_v3/resolvers/comment_stream_test.exs
- This was inadvertently using the comment preloads. Instead, we will
use the default post preloads when finding the post
> Don’t include the entire args map when finding the post

- apps/ello_notifications/lib/ello_notifications/stream.ex
- apps/ello_notifications/lib/ello_notifications/stream/loader.ex
- apps/ello_notifications/mix.exs
- apps/ello_v3/lib/ello_v3/resolvers/notification_stream.ex
- apps/ello_v3/lib/ello_v3/schema/notification_types.ex
The notification streams service returns an unusual datetime format, so
don't just pass it through as is. Instead we parse and re-format into
the same format all graphql dates are in.
> Ensure notification created_at is formatted right

- apps/ello_core/lib/ello_core/network/user.ex
- apps/ello_events/lib/ello_events/mark_notifications_as_read.ex
- apps/ello_notifications/lib/ello_notifications/stream/client/http.ex
Subject queries will handled blocked requests anyway, so this is mainly
to reduce handling the issue after the query instead of before.
> Limit excluded ids in notification api call.
