ello/apex

- apps/ello_serve/web/templates/webapp/post/noscript.html.eex
- apps/ello_serve/web/views/webapp/post_view.ex
We should just handle this gracefully in the pre-render sections.
> Handle missing content due to render fails.

- apps/ello_serve/lib/ello_serve/find_user.ex
- apps/ello_serve/lib/ello_serve/skip_prerender.ex
- apps/ello_serve/test/controllers/webapp/post_controller_test.exs
- apps/ello_serve/test/controllers/webapp/user_controller_test.exs
- apps/ello_serve/web/controllers/webapp/post_controller.ex
- apps/ello_serve/web/controllers/webapp/user_controller.ex
Also adds tests around them. https://www.pivotaltracker.com/story/show/148701501
> Fix private 404s

- apps/ello_serve/lib/ello_serve/version_store/slack_notfications.ex
[Fixes #148775643](https://www.pivotaltracker.com/story/show/148775643)
> Fix the compare links that get dropped into slack

- apps/ello_core/lib/ello_core/contest.ex
- apps/ello_core/lib/ello_core/contest/artist_invite.ex
- apps/ello_core/lib/ello_core/contest/artist_invite_submission.ex
- apps/ello_core/lib/ello_core/contest/preload.ex
- apps/ello_core/priv/repo/migrations/20170713180443_create_artists_invite_submissions.exs
- apps/ello_core/test/support/factory.ex
- apps/ello_events/lib/ello_events/track_post_views.ex
- apps/ello_v2/lib/ello_v2/conditional_get.ex
- apps/ello_v2/lib/ello_v2/pagination.ex
- apps/ello_v2/test/controllers/artist_invite_submission_controller_test.exs
- apps/ello_v2/test/views/artist_invite_submission_view_test.exs
- apps/ello_v2/test/views/artist_invite_view_test.exs
- apps/ello_v2/web/controllers/artist_invite_submission_controller.ex
- apps/ello_v2/web/router.ex
- apps/ello_v2/web/views/artist_invite_submission_view.ex
- apps/ello_v2/web/views/artist_invite_view.ex
> Artist invite submission read API.

- apps/ello_core/lib/ello_core.ex
- apps/ello_core/lib/ello_core/content.ex
- apps/ello_core/lib/ello_core/discovery.ex
- apps/ello_core/lib/ello_core/network.ex
- apps/ello_core/test/support/factory.ex
- apps/ello_serve/test/controllers/webapp/love_controller_test.exs
- apps/ello_serve/test/controllers/webapp/no_content_controller_test.exs
- apps/ello_serve/test/controllers/webapp/relationship_controller_test.exs
- apps/ello_serve/web/controllers/webapp/relationship_controller.ex
- apps/ello_serve/web/router.ex
- apps/ello_serve/web/templates/webapp/relationship/noscript.html.eex
- apps/ello_serve/web/views/webapp/love_view.ex
- apps/ello_serve/web/views/webapp/relationship_view.ex
- apps/ello_v2/test/controllers/editorials_controller_test.exs
> Properly encode and parse before in next link.

- apps/ello_serve/config/config.exs
- apps/ello_serve/lib/ello_serve/default_to_html.ex
- apps/ello_serve/test/ello_serve/default_to_html_test.exs
> Force HTML for text/* for real.

- apps/ello_serve/lib/ello_serve/x_frame_options.ex
- apps/ello_serve/web/router.ex
To prevent clickjacking etc.
https://www.pivotaltracker.com/story/show/149594913
> Break out of frames.

- apps/ello_serve/web/controllers/webapp/artist_invite_show_controller.ex
- apps/ello_serve/web/templates/webapp/artist_invite_index/noscript.html.eex
- apps/ello_serve/web/templates/webapp/artist_invite_show/noscript.html.eex
We were not tracking submission post views in serve, and I noticed that we were displaying markdown in the browser.
> Artist Invite Fixes

- apps/ello_core/lib/ello_core/contest/preload.ex
- apps/ello_v2/lib/ello_v2/conditional_get.ex
- apps/ello_v2/test/controllers/artist_invite_controller_test.exs
- apps/ello_v2/test/views/artist_invite_view_test.exs
- apps/ello_v2/web/views/artist_invite_view.ex
https://www.pivotaltracker.com/story/show/149321741
> Artist Invite schema validations

- apps/ello_core/lib/ello_core/content.ex
- apps/ello_core/lib/ello_core/content/filter.ex
- apps/ello_core/lib/ello_core/content/preload.ex
- apps/ello_core/test/ello_core/content_test.exs
- apps/ello_v2/test/controllers/comment_controller_test.exs
- apps/ello_v2/test/views/comment_view_test.exs
- apps/ello_v2/web/controllers/comment_controller.ex
- apps/ello_v2/web/router.ex
- apps/ello_v2/web/views/comment_view.ex
https://www.pivotaltracker.com/story/show/149570237
> Add comment read endpoints.

- apps/ello_feeds/web/controllers/editorial_controller.ex
- apps/ello_serve/web/controllers/webapp/discover_post_controller.ex
- apps/ello_serve/web/controllers/webapp/editorial_controller.ex
- apps/ello_serve/web/controllers/webapp/love_controller.ex
- apps/ello_serve/web/controllers/webapp/post_controller.ex
- apps/ello_serve/web/controllers/webapp/search_controller.ex
- apps/ello_serve/web/controllers/webapp/user_controller.ex
😊 😞 ⌨️ :-1:
Wow. My bad. 
This will have lead to some misreporting of stream kind, but the impressions themselves would still be captured.
> Fix stream_kind typo.

- apps/ello_core/lib/ello_core/contest/artist_invite.ex
- apps/ello_core/lib/ello_core/contest/artist_invite/og_image.ex
- apps/ello_core/priv/repo/migrations/20170707165737_create_artist_invite_table.exs
- apps/ello_core/test/support/factory.ex
- apps/ello_serve/test/controllers/webapp/artist_invite_index_controller_test.exs
- apps/ello_serve/test/controllers/webapp/artist_invite_show_controller_test.exs
- apps/ello_serve/web/controllers/webapp/artist_invite_show_controller.ex
- apps/ello_serve/web/views/webapp/artist_invite_index_view.ex
- apps/ello_serve/web/views/webapp/artist_invite_show_view.ex
- apps/ello_serve/web/views/webapp/post_view.ex
(And one repost indexing tweak).
> Artist Invite seo tweaks

- apps/ello_v2/lib/ello_v2/pagination.ex
- apps/ello_v2/test/controllers/user_post_controller_test.exs
https://www.pivotaltracker.com/story/show/150312428
> Only add link header if not last page.

- apps/ello_core/test/support/factory.ex
- apps/ello_events/lib/ello_events/track_post_views.ex
- apps/ello_serve/test/controllers/webapp/editorial_controller_test.exs
- apps/ello_serve/web/templates/webapp/editorial/artist_invite_editorial.html.eex
- apps/ello_serve/web/views/webapp/editorial_view.ex
- apps/ello_v2/test/controllers/artist_invite_submission_controller_test.exs
- apps/ello_v2/test/views/editorial_view_test.exs
- apps/ello_v2/web/controllers/artist_invite_submission_controller.ex
- apps/ello_v2/web/router.ex
- apps/ello_v2/web/views/editorial_view.ex
https://www.pivotaltracker.com/story/show/150312249
> Artist invite editorial

- apps/ello_core/lib/ello_core/discovery/promotional.ex
- apps/ello_core/priv/repo/migrations/20161207032414_create_promotion.exs
- apps/ello_core/test/support/factory.ex
- apps/ello_v2/test/views/promotional_view_test.exs
- apps/ello_v2/web/views/promotional_view.ex
https://www.pivotaltracker.com/story/show/150228401
> Track promo views.

- apps/ello_core/lib/ello_core/contest.ex
- apps/ello_v2/test/controllers/artist_invite_submission_controller_test.exs
- apps/ello_v2/test/views/artist_invite_submission_view_test.exs
- apps/ello_v2/test/views/artist_invite_view_test.exs
- apps/ello_v2/web/views/artist_invite_submission_view.ex
- apps/ello_v2/web/views/artist_invite_view.ex
https://www.pivotaltracker.com/story/show/150862418
> Support declined submissions

- apps/ello_core/lib/ello_core/contest.ex
- apps/ello_v2/test/controllers/manage/artist_invite_controller_test.exs
- apps/ello_v2/web/controllers/manage/artist_invite_controller.ex
- apps/ello_v2/web/router.ex
TODO:
https://www.pivotaltracker.com/story/show/151996297
> Manage Artist Invites Endpoint

- apps/ello_core/lib/ello_core/contest/artist_invite.ex
- apps/ello_core/priv/repo/migrations/20170707165737_create_artist_invite_table.exs
- apps/ello_v2/test/controllers/manage/artist_invite_controller_test.exs
- apps/ello_v2/web/controllers/manage/artist_invite_controller.ex
- apps/ello_v2/web/views/manage/artist_invite_view.ex
Also removes unused data from response.
> Adds custom stats to ArtistInvite data.

- apps/ello_serve/test/controllers/webapp/no_content_controller_test.exs
- apps/ello_serve/web/router.ex
> Fix forgot password url.

- apps/ello_events/lib/ello_events/track_post_views.ex
- apps/ello_serve/web/views/webapp/editorial_view.ex
- apps/ello_v2/web/controllers/editorial_post_controller.ex
- apps/ello_v2/web/controllers/editorials_controller.ex
https://www.pivotaltracker.com/story/show/153880246
> Editorial post view tracking fixes

- apps/ello_v2/lib/ello_v2/client_properties.ex
- apps/ello_v2/test/ello_v2/client_properties_test.exs
https://www.pivotaltracker.com/story/show/154262574
> Do not allow NSFW for webapp

- apps/ello_core/lib/ello_core/content/post.ex
- apps/ello_core/lib/ello_core/content/preload.ex
- apps/ello_core/lib/ello_core/network/preload.ex
- apps/ello_v3/lib/ello_v3/middleware/standardize_arguments.ex
- apps/ello_v3/lib/ello_v3/resolvers/find_post.ex
- apps/ello_v3/lib/ello_v3/schema/content_types.ex
- apps/ello_v3/lib/ello_v3/schema/contest_types.ex
- apps/ello_v3/lib/ello_v3/schema/network_types.ex
- apps/ello_v3/test/ello_v3/resolvers/find_post_test.exs
- apps/ello_v3/test/ello_v3/resolvers/user_post_stream_test.exs
- apps/ello_v3/test/test_helper.exs
They are now only actually preloaded when the data is requested, however
v2 still gets the full preload.
> Optimize v3 post and user preloads.

- apps/ello_core/lib/ello_core/network/user.ex
- apps/ello_core/priv/repo/migrations/20161208040450_create_user.exs
- apps/ello_v3/lib/ello_v3/resolvers/user_categories.ex
- apps/ello_v3/lib/ello_v3/schema.ex
- apps/ello_v3/lib/ello_v3/schema/discovery_types.ex
- apps/ello_v3/test/ello_v3/resolvers/user_categories_test.exs
- Adds followed_category_ids to user model
https://www.pivotaltracker.com/story/show/154940047
> Add categoryNav endpoint

- apps/ello_core/lib/ello_core/discovery.ex
- apps/ello_core/lib/ello_core/discovery/page_promotional.ex
- apps/ello_core/lib/ello_core/discovery/preload.ex
- apps/ello_core/priv/repo/migrations/20180207154309_create_page_promotionals.exs
- apps/ello_core/test/support/factory.ex
- apps/ello_v3/lib/ello_v3/middleware/standardize_arguments.ex
- apps/ello_v3/lib/ello_v3/resolvers/page_headers.ex
- apps/ello_v3/lib/ello_v3/schema.ex
- apps/ello_v3/lib/ello_v3/schema/discovery_types.ex
- apps/ello_v3/test/ello_v3/resolvers/find_post_test.exs
- apps/ello_v3/test/ello_v3/resolvers/page_headers_test.exs
- apps/ello_v3/test/ello_v3/schema_test.exs
https://www.pivotaltracker.com/story/show/154940082
> Add page headers v3 query.

- apps/ello_v3/lib/ello_v3/resolvers/categories.ex
- apps/ello_v3/lib/ello_v3/schema.ex
- apps/ello_v3/test/ello_v3/resolvers/categories_test.exs
https://www.pivotaltracker.com/story/show/154940052
> Add allCategories endpoint

- apps/ello_core/lib/ello_core/content/preload.ex
- apps/ello_core/lib/ello_core/network/preload.ex
- apps/ello_serve/lib/ello_serve/standard_params.ex
- apps/ello_stream/lib/ello_stream.ex
- apps/ello_v2/lib/ello_v2/standard_params.ex
- apps/ello_v3/lib/ello_v3/middleware/standardize_arguments.ex
- apps/ello_v3/lib/ello_v3/resolvers/category_post_stream.ex
- apps/ello_v3/lib/ello_v3/resolvers/global_post_stream.ex
- apps/ello_v3/lib/ello_v3/resolvers/pagination_helpers.ex
- apps/ello_v3/lib/ello_v3/resolvers/user_post_stream.ex
- apps/ello_v3/lib/ello_v3/schema.ex
- apps/ello_v3/lib/ello_v3/schema/content_types.ex
- apps/ello_v3/lib/ello_v3/schema/discovery_types.ex
- apps/ello_v3/test/ello_v3/resolvers/category_post_stream_test.exs
- apps/ello_v3/test/ello_v3/resolvers/global_post_stream_test.exs
- apps/ello_v3/test/ello_v3/resolvers/user_categories_test.exs
- apps/ello_v3/test/ello_v3/resolvers/user_post_stream_test.exs
- apps/ello_v3/test/ello_v3/schema_test.exs
> Global post streams

- apps/ello_v3/lib/ello_v3/middleware/standardize_arguments.ex
- apps/ello_v3/lib/ello_v3/resolvers/category_post_stream.ex
- apps/ello_v3/lib/ello_v3/schema.ex
- apps/ello_v3/lib/ello_v3/schema/content_types.ex
- apps/ello_v3/test/ello_v3/resolvers/category_post_stream_test.exs
- apps/ello_v3/test/ello_v3/schema_test.exs
https://www.pivotaltracker.com/story/show/154940601
> Add category post stream endpoint

- apps/ello_v3/lib/ello_v3/schema/content_types.ex
@colinta @Justin-Holmes Can we take this opportunity to talk about reposts a bit?
Is the "Fix" I added below really the right fix? Why do we ever overwrite properties on the repost when we have the original post as well?
The only time I think that could be considered relevant is if we are worrying about the content itself being changed and storing a copy of the reposted content. The one place I think we SHOULD do it, loved, reposted, and watching, we don't.
How do you folks feel about how we handle reposts in the API?
> "Fix" repost stats.

- apps/ello_v3/lib/ello_v3/resolvers/find_post.ex
- apps/ello_v3/lib/ello_v3/resolvers/global_post_stream.ex
- apps/ello_v3/lib/ello_v3/resolvers/post_view_helpers.ex
- apps/ello_v3/lib/ello_v3/resolvers/user_post_stream.ex
- apps/ello_v3/mix.exs
This is pretty tough to test unfortunately. We may just have to verify on staging or something.
> Add post view tracking support.

- apps/ello_search/lib/ello_search/post/search.ex
- apps/ello_search/test/ello_search/post/search_test.exs
- apps/ello_serve/web/views/webapp/editorial_view.ex
- apps/ello_v2/web/controllers/category_post_controller.ex
- apps/ello_v3/lib/ello_v3/resolvers/category_post_stream.ex
- apps/ello_v3/lib/ello_v3/resolvers/pagination_helpers.ex
- apps/ello_v3/lib/ello_v3/resolvers/subscribed_post_stream.ex
- apps/ello_v3/lib/ello_v3/resolvers/user_post_stream.ex
- apps/ello_v3/lib/ello_v3/schema.ex
- apps/ello_v3/lib/ello_v3/schema/content_types.ex
- apps/ello_v3/test/ello_v3/resolvers/category_post_stream_test.exs
- apps/ello_v3/test/ello_v3/resolvers/subscribed_post_stream_test.exs
https://www.pivotaltracker.com/story/show/154940601
> Subscribed cat stream

- apps/ello_core/lib/ello_core/content/preload.ex
> Fix repost counts in v2 api.

- apps/ello_core/lib/ello_core/discovery.ex
- apps/ello_core/lib/ello_core/discovery/page_promotional.ex
- apps/ello_core/priv/repo/migrations/20180207154309_create_page_promotionals.exs
- apps/ello_core/test/support/factory.ex
- apps/ello_v3/lib/ello_v3/resolvers/page_headers.ex
- apps/ello_v3/lib/ello_v3/schema/discovery_types.ex
- apps/ello_v3/test/ello_v3/resolvers/page_headers_test.exs
https://www.pivotaltracker.com/story/show/155413671
> Add “is_authentication” to page headers and page promos

- apps/ello_core/lib/ello_core/content/preload.ex
- apps/ello_core/lib/ello_core/contest.ex
- apps/ello_core/lib/ello_core/discovery.ex
- apps/ello_core/lib/ello_core/network/category_user.ex
- apps/ello_core/lib/ello_core/network/preload.ex
- apps/ello_core/lib/ello_core/network/user.ex
- apps/ello_core/priv/repo/migrations/20180502222500_create_category_users.exs
- apps/ello_core/test/ello_core/network_test.exs
- apps/ello_core/test/support/factory.ex
- apps/ello_search/lib/ello_search/post/index.ex
- apps/ello_v2/test/controllers/category_controller_test.exs
- apps/ello_v2/test/controllers/manage/submission_count_controller_test.exs
- apps/ello_v2/test/controllers/user_controller_test.exs
- apps/ello_v2/test/views/user_view_test.exs
https://www.pivotaltracker.com/story/show/156727947
> Category user

- apps/ello_core/lib/ello_core/discovery.ex
- apps/ello_core/lib/ello_core/network/preload.ex
- apps/ello_v3/lib/ello_v3/middleware/standardize_arguments.ex
- apps/ello_v3/lib/ello_v3/resolvers/category_users.ex
- apps/ello_v3/lib/ello_v3/resolvers/find_user.ex
- apps/ello_v3/lib/ello_v3/schema.ex
- apps/ello_v3/lib/ello_v3/schema/network_types.ex
- apps/ello_v3/test/ello_v3/resolvers/find_user_test.exs
- apps/ello_v3/test/ello_v3/schema_test.exs
Also adds support for categoryUser when querying users.
> Add findUser graphql query.

- apps/ello_core/lib/ello_core/content/preload.ex
- apps/ello_v3/lib/ello_v3/middleware/standardize_arguments.ex
- apps/ello_v3/lib/ello_v3/resolvers/comment_stream.ex
- apps/ello_v3/lib/ello_v3/schema.ex
- apps/ello_v3/lib/ello_v3/schema/content_types.ex
- apps/ello_v3/test/ello_v3/resolvers/comment_stream_test.exs
https://www.pivotaltracker.com/story/show/157823175
> Add comments graphql endpoint

- apps/ello_core/lib/ello_core/content.ex
- apps/ello_core/lib/ello_core/content/love.ex
- apps/ello_core/lib/ello_core/content/preload.ex
- apps/ello_v3/lib/ello_v3/middleware/standardize_arguments.ex
- apps/ello_v3/lib/ello_v3/resolvers/user_love_stream.ex
- apps/ello_v3/lib/ello_v3/schema.ex
- apps/ello_v3/lib/ello_v3/schema/content_types.ex
- apps/ello_v3/test/ello_v3/resolvers/user_love_stream_test.exs
https://www.pivotaltracker.com/story/show/157608930
> Add GraphQL endpoint for a user’s love stream

- apps/ello_search/lib/ello_search/user/search.ex
- apps/ello_v3/lib/ello_v3/middleware/standardize_arguments.ex
- apps/ello_v3/lib/ello_v3/resolvers/search_users.ex
- apps/ello_v3/lib/ello_v3/schema.ex
- apps/ello_v3/lib/ello_v3/schema/network_types.ex
- apps/ello_v3/test/ello_v3/resolvers/search_users_test.exs
- apps/ello_v3/test/ello_v3/schema_test.exs
For an easier to customize username auto-completer.
> Add user search via graphql.

- apps/ello_v3/lib/ello_v3/resolvers/notification_stream.ex
- apps/ello_v3/test/ello_v3/resolvers/notification_stream_test.exs
hd() list errors on empty notifications
> Handle empty notifications.

- .gitignore
- LICENSE.txt
- README.md
- apps/ello_core/config/config.exs
- apps/ello_core/lib/ello_core/network/user.ex
- apps/ello_core/lib/ello_core/network/user/settings.ex
- apps/ello_core/priv/repo/migrations/20161208040450_create_user.exs
- apps/ello_v3/lib/ello_v3/resolvers/profile.ex
- apps/ello_v3/lib/ello_v3/schema.ex
- apps/ello_v3/lib/ello_v3/schema/network_types.ex
- apps/ello_v3/test/ello_v3/resolvers/profile_test.exs
> OMG it's a GraphQL endpoint from Colin
